from pathlib import Path
from datetime import datetime
import os


# ---------------------------------
# Generate Documentation
# ---------------------------------
def generate_documentation(repo_path):

    os.makedirs(
        "static",
        exist_ok=True
    )

    repository_name = repo_path.split("/")[-1]

    if repository_name == "temp_repo":

        repository_name = "Analyzed Repository"

    python_files = list(

        Path(repo_path).rglob(

            "*.py"

        )

    )

    # Remove unnecessary files

    python_files = [

        file

        for file in python_files

        if "__pycache__" not in str(file)

        and "__init__.py" not in file.name

        and "test" not in str(file).lower()

        and "alembic" not in str(file).lower()

        and "migration" not in str(file).lower()

        and ".copier" not in str(file)

        and "hooks" not in str(file).lower()

        and "scripts" not in str(file).lower()

    ]

    documentation = []

    documentation.append(

        "# Repository Documentation\n"

    )

    documentation.append(

        f"Repository Name: {repository_name}\n"

    )

    documentation.append(

        f"Total Python Files: {len(python_files)}\n"

    )

    documentation.append(

        "## Project Structure\n"

    )

    for file in python_files:

        try:

            with open(

                file,

                "r",

                encoding="utf-8"

            ) as f:

                lines = f.readlines()

            documentation.append(

                f"### {file.name}"

            )

            documentation.append(

                f"- Path: {file}"

            )

            documentation.append(

                f"- Lines of Code: {len(lines)}"

            )

            imports = []

            for line in lines:

                line = line.strip()

                if line.startswith(

                    "import "

                ):

                    imports.append(

                        line

                    )

                elif line.startswith(

                    "from "

                ):

                    imports.append(

                        line

                    )

            if imports:

                documentation.append(

                    "- Imports:"

                )

                for item in imports:

                    documentation.append(

                        f"  - {item}"

                    )

            documentation.append("")

        except Exception:

            pass

    documentation.append(

        "\n## Workflow\n"

    )

    documentation.append(

"""
GitHub URL

↓

Clone Repository

↓

Scan Files

↓

Dependency Graph

↓

AI Analysis

↓

Architecture Diagram

↓

Documentation Generation
"""
    )

    documentation.append(

        "\n## Generated By\n"

    )

    documentation.append(

        "Git-Detective"

    )

    documentation.append(

        f"Generated At: {datetime.now().strftime('%d %b %Y, %I:%M %p')}"

    )

    output_file = (

        "static/PROJECT_DOCUMENTATION.md"

    )

    with open(

        output_file,

        "w",

        encoding="utf-8"

    ) as f:

        f.write(

            "\n".join(

                documentation

            )

        )

    return output_file


# ---------------------------------
# Test
# ---------------------------------
if __name__ == "__main__":

    generate_documentation(

        "temp_repo"

    )